src/scenes/gameplay-scene.ts

Added clearTimeout handling setTimeout reset animation to idle for wordPuzzle game.
Modified File(s)
1. gameplay-scene.ts

Fixed [FM-7]: Fixed issue where spit animation not properly playing on word puzzle if you play the game very quick.

---

src/common/stone-config.ts

There is a white outline around the stones in Unity FTM that is not present in FTMJs.
Added shadow outline to stones in gameplay screen.

FM-52 White highlighting around stone

---

src/components/trail-particles.ts

feat<fm-51>: Hover trail effect -> Updated the trail effect by increasing size and used the diamond shape instead of the circle shape.
- Updated size and x and y coordinates for trail-particles.ts.
- Switch the shape method by using the draw diamond instead of circle.
- Start FTM app
- Select any level in level selection.
- In the game just press and hover or drag letters, trail effect should be visible.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-51)

feat<fm-51>: Hover trail effect -> Updated the trail effect

---

src/scenes/level-selection-scene.ts

feat<FM-256>: Create reusable level button -> Fixed incorrect object attribute size for rendering debug level indicator.
- level-selection-scene.ts -> Updated incorrect level size value.
- Run FTM then press dev button to enable developer mode.
- Then press start button and all levels should be unlocked with the game level text displayed at the bottom of each buttons.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-256)

feat<FM-256>: Create reusable level button

---

src/sceneHandler/index.ts

- src/sceneHandler/index.ts
- make sure feedback text will still appear after switching to end level
Ref: [FM-69](https://curiouslearning.atlassian.net/browse/FM-69)
[FM-69]: https://curiouslearning.atlassian.net/browse/FM-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: fix z index to feedback text in level end screen (FM-69)

---

src/scenes/gameplay-scene.ts

- gameplay-scene.ts
- Run FTM on local
- Press start followed by selecting letter only level
- In gameplay, drag one of the letter stones and the monster's mouth should open
- Drag the stone anywhere and drop it except in the monster's mouth, it should close it's mouth when no stones where given to it.
- When given the next game stage should still have the same behavior 
- Exit the game and select word play level
- In word play level, follow the same logic in 4 and 5, and it should reset whenever correct or failed letter was drop.
Ref: [[JIRA-CODE](https://curiouslearning.atlassian.net/browse/JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-258))

Bug<FM-258>: After selecting a stone, the Monster's mouth stays open even after leaving the stone without giving the input

---

src/components/stone-handler.ts
src/gamepuzzles/index.ts
src/gamepuzzles/wordPuzzleLogic.ts
src/scenes/gameplay-scene.ts
tsconfig.json
webpack.config.js

- Added multi-letter selection for word puzzle.
- Moved conditions relating to word puzzle to a separate class.
- Moved conditions of updating coordinates to stone-handler class.
Enable dev mode
- Option 1
1. In our FTM source code navigate to src/common/global-variables.ts.
2. Set the DebugMode from 'false' to 'true'.
3. Run the application with 'npm run dev' and in another cmd the command 'workbox injectManifest'.
4. Right click on the build/index.html and open it with LiveServer.
5. Game should run in developer mode with puzzle names indicated on level-selection.
- Option 2
1. On the start screen of the FTM app there is a gray button 'DEV'.
2. Press the 'DEV' button to enable the developer mode.
3. Game should run in developer mode with puzzle names indicated on level-selection.
After …

Feat<FM-276>: Word Puzzle Multi-Letter Selection Feature

---

src/components/buttons/level-button.ts
src/scenes/level-selection-scene.ts

- Created a pulse effect on current level icon
- Tap or click any part of the start screen to proceed to the next screen.
- On the level selection screen, ensure that the current level icon has a pulse effect animation.
Ref: [FM-271](https://curiouslearning.atlassian.net/browse/FM-271)
[FM-271]: https://curiouslearning.atlassian.net/browse/FM-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: subtle attention drawing animation on level icons (FM-271)

---

index.css
src/components/feedback-text/index.ts

- Fixed the issue on feedback text in some tablet device
- In start screen
- On the level selection screen, select any level icon to play
- On the game screen, select a correct word or stone
- Make sure the feedback text fits properly in devices/tablet
Ref: [FM-278](https://curiouslearning.atlassian.net/browse/FM-278)
[FM-278]: https://curiouslearning.atlassian.net/browse/FM-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: ensure feedback text effect fits properly in all devices (FM-278)

---

build/index.css
index.css
package.json
src/components/popups/base-popup/base-popup-component.ts
webpack.config.js

- new: BasePopupComponent class implementation
- update: added css styles for html popup
- chore: added workbox script in package.json
- import BasePopupComponent to any page
```
const popup = new BasePopupComponent ();
popup.show();
```
- popup should be visible
- close button should be clickale
- clicking should close popup
Note: this is a base class and not meant for direct use. Actual usage would require creating a child class, extending this class.
i.e.
```
export class PausePopupComponent extends BasePopupComponent  {
template = `
... // popup contents here
`
}
```
Ref: [FM-297](https://curiouslearning.atlassian.net/browse/FM-297)
[FM-297]: https://curiouslearning.atlassian.net/browse/FM-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: BasePopupComponent class implementation (FM-297)

---

src/components/popups/pause-popup.ts

- Added pause publish to pause-popup no retry callback.
- Start Game and make sure it is in English language
- Select any level
- In game play, press pause on upper right.
- A popup will appear and then select retry button.
- Another popup will appear and select no to cancel retry.
- The game should unpaused allowing you to continue the game
Ref: [FM-285](https://curiouslearning.atlassian.net/browse/FM-285)
[FM-285]: https://curiouslearning.atlassian.net/browse/FM-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fm-285: Added pause publishing to false in no-retry-callback.

---

public/index.html
src/Firebase/firebase-event-interface.ts
src/Firebase/firebase-integration.ts
src/components/buttons/index.ts
src/components/buttons/next-button/next-button.ts
src/sceneHandler/scene-handler.ts
src/scenes/gameplay-scene.ts
src/scenes/index.ts
src/scenes/levelend-scene/levelend-scene.scss
src/scenes/levelend-scene/levelend-scene.spec.ts
src/scenes/levelend-scene/levelend-scene.ts

- Use HTML buttons into level end screen
- Move levelend-scene.ts to src/scenes/levelend-scene/levelend-scene.ts
- Created next button component
- Select any level to play
- Finish the game
- Make sure the buttons are html and working properly
Ref: [FM-328](https://curiouslearning.atlassian.net/browse/FM-328)
[FM-328]: https://curiouslearning.atlassian.net/browse/FM-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Refactor all the buttons on Level End screen from canvas to HTML  (FM-328)

---

jest.config.js
package-lock.json
package.json
src/components/popups/pause-popup/pause-popup-component.ts
src/gameStateService/data-access-objects.ts
src/scenes/gameplay-scene.ts
tsconfig.json

- Refactor the gameplay-scene - handleMouseUp method on resetting and adjusting the stone X position.
- Moved the + 25 offset adjustment to staticCoordinateFactors so the offset will be added upon creation.
- Start the FTM app and press play on start screen.
- Select any level on level selection.
- During the game play, the stones on the left should not adjust their original position and should return to how they are originally displayed.
Ref: [FM-331](https://curiouslearning.atlassian.net/browse/FM-331)
[FM-331]: https://curiouslearning.atlassian.net/browse/FM-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Fixed the left stones from adjusting their original X position (FM-331).

---

public/index.css

- Fix feedback text overlapping in level end scene
- Play any level
- Finish the game
- Make sure the feedback text is not overlapping in the level scene
Ref: [FM-341](https://curiouslearning.atlassian.net/browse/FM-341)
[FM-341]: https://curiouslearning.atlassian.net/browse/FM-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix - feedback text overlap in levelend scene (FM-341)

---

public/index.css

- fix image can be dragged all over the screen
- Select any level to play
- In the Gameplay Scene try dragging all UI elements that we just converted to html recently
- Make sure you cannot drag those UI elements
Ref: [FM-344](https://curiouslearning.atlassian.net/browse/FM-344)
[FM-344]: https://curiouslearning.atlassian.net/browse/FM-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: images are draggable all over the screen (FM-344)

---

src/components/buttons/play-button/play-button.scss
src/scenes/start-scene/start-scene.spec.ts
src/scenes/start-scene/start-scene.ts

- Updated the CSS implementation of Play Button so it will be on top of the canvas and pressable.
- Added routing logic to the Play Button.
- Updated the test cases for the start-scene press play scenario.
- Start the FTM.
- On the Start Scene, the play button should be pressable now as it will animate a press down.
- It should also play an audio as you press it.
- It should switch to level selection properly.
Ref: [FM-291](https://curiouslearning.atlassian.net/browse/FM-291)
[FM-291]: https://curiouslearning.atlassian.net/browse/FM-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Add screen transition (routing) analytics and event handling on the Start Scene (FM-291).

---

src/components/timer-ticking.ts
src/components/timerHtml/timerHtml.spec.ts
src/scenes/gameplay-scene/gameplay-scene.ts
src/scenes/start-scene/start-scene.spec.ts
src/scenes/start-scene/start-scene.ts

- Updated logic on play button, adding the hiding of toggle button.
- Updated timer-ticking destroy method by adding this.timerHtmlComponent?.destroy(); as part of its logic so HTML element can be removed properly.
- Updated test cases for start-scene and timer-ticking.
- For FM-288, on start screen, pressing play button should make the dev button disappear.
- For FM-347, there should be no duplicate timer HTML whenever the game restarts. Press F12 and see if element 'timer-ticking' is under background HTML, it should only be one.
Ref: [FM-288](https://curiouslearning.atlassian.net/browse/FM-288)
Ref: [FM-347](https://curiouslearning.atlassian.net/browse/FM-347)
[FM-288]: https://curiouslearning.atlassian.net/browse/FM-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

fixes: Fixed dev button not disappearing when play button is pressed and timer HTML duplication issue. (FM-288 & FM-347)

---

src/feedTheMonster.ts
src/scenes/start-scene/start-scene.spec.ts
src/scenes/start-scene/start-scene.ts

- Removed setting of loadingElement display to "none", from FeedTheMonster and moved the logic to Start-scene.
- Updated start-scene test case and create a new scenario for start scene initial loading.
- Load The FTM.
- During the loading before the start scene, there should be no brief black screen.
Ref: [FM-348](https://curiouslearning.atlassian.net/browse/FM-348)
[FM-348]: https://curiouslearning.atlassian.net/browse/FM-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fixed black screen when start scene renders (FM-348).

---

src/scenes/gameplay-scene/gameplay-scene.ts
src/scenes/level-selection-scene.ts

- When the stones appear if we select one stone and we don't drop it to the monster and if we try to drop a different stone then the reaction animations are not playing.
- If we click on the stone multiple times the monster mouth open animation plays and it will be in that stage even if we don't hold the stone and until we drop a stone.
- If we click on the stone position the monster mouth open animation plays.
- If we give fast inputs to the monster sometimes the reaction animation gets stuck.
Ref: [FM-267](https://curiouslearning.atlassian.net/browse/FM-267)
[FM-267]: https://curiouslearning.atlassian.net/browse/FM-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fm 267 Animation issues fixed on gameplay screen

---

src/common/stone-config.ts

- src/common/stone-config.ts
- The stone text should look in normal size.
Ref: [CR-257](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-257)
[CR-257]: https://curiouslearning.atlassian.net/browse/CR-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: changes reverted for CR-257 stone text issue PR

---

src/components/prompt-text.ts

- Check for Letteronly levels in RTL
Ref: [CR-286](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-286)
[CR-286]: https://curiouslearning.atlassian.net/browse/CR-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Cr 286 LetterOnly alignment issue

---

src/Firebase/base-firebase-integration.ts
src/Firebase/firebase-integration.ts
src/components/buttons/play-button.ts
src/scenes/start-scene.ts

- Renaming "user_clicked" event to "tapped_start"!
- in order to test the changes user can open the big-querry, after running querries user can see the event being logged as "tapped_start"!
Ref: [AJ-299](https://curiouslearning.atlassian.net/browse/AJ-299)
[AJ-299]: https://curiouslearning.atlassian.net/browse/AJ-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Renaming "user_clicked" event to "tapped_start"!

---

src/components/prompt-text/prompt-text.scss
src/components/prompt-text/prompt-text.ts

- Fixed the extra spacing in RTL languages
- Run any RTL languages
- Select and play the word game
- Make sure there's no extra spaces in the word
Ref: [Fm-463](https://curiouslearning.atlassian.net/browse/Fm-463)

fix: rtl spacing fix (Fm-463)

---

src/components/prompt-text/prompt-text.ts
src/scenes/gameplay-scene/gameplay-scene.ts

- Fix the highlighting issues when one foil stone has more than 1 characters
- Select any word level and play (Example language: Hausa - lvl 50)
- Make sure the text unhighlighted properly
Ref: [FM-463](https://curiouslearning.atlassian.net/browse/FM-463)
[FM-463]: https://curiouslearning.atlassian.net/browse/FM-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: the prompt text highlighting when it has more than 1 or more characters in foilstones (FM-463)

---

src/components/stone-handler/stone-handler.ts

- The screen and the canvas is getting zoomed in FTM app.
- Download and install the dev version of the FTM app.
- Navigate to the FTM app and select a level and start playing the game.
- Then click on pause button and click on any button level-selection or replay button.
- We can observe that the cloud animation won’t play properly and the zoomed out issue.
Ref: [FM-491](https://curiouslearning.atlassian.net/browse/FM-491)
[FM-491]: https://curiouslearning.atlassian.net/browse/FM-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: FM-491 The screen and the canvas is getting zoomed in FTM app.

---

lang/australianenglish/ftm_australianenglish.json
package.json

- Feedback audios are not playing in Australian English test build.
- Fixed the typo in Australian English json file
Ref: [FM-489](https://curiouslearning.atlassian.net/browse/Fm-489)
[FM-489]: https://curiouslearning.atlassian.net/browse/FM-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: FM-489 Feedback audios are not playing in Australian English test build.

---

src/components/evolutionAnimation/evolution-animation.spec.ts
src/components/evolutionAnimation/evolution-animation.ts

-  preload audios plays and minimize delay in the evolution screen
Ref: [FM-504](https://curiouslearning.atlassian.net/browse/FM-504)
[FM-504]: https://curiouslearning.atlassian.net/browse/FM-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: The intro audio plays in the background in Gameplay screen and other screen. (FM-504)

---

src/components/prompt-text/prompt-text.spec.ts
src/components/prompt-text/prompt-text.ts

- fix the double Letter word highlighted text im text prompt component
- Open the start screen of FTM (ndebele language).
- press level 6
- make sure that it only highlights the first letter of the word
Ref: [FM-530](https://curiouslearning.atlassian.net/browse/FM-530)
[FM-530]: https://curiouslearning.atlassian.net/browse/FM-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: double Letter word highlighted text (FM-530)

---

src/constants/index.ts
src/sceneHandler/scene-handler.ts
src/scenes/gameplay-scene/gameplay-scene.ts

- Added handling on scene handling for gameplay and game repeat to make sure it will work on the logic for preventing redundant scene initialization.
- FTM redirection should work.
- App should not break on stress testing.
Ref: [FM-532](https://curiouslearning.atlassian.net/browse/FM-532)
[FM-532]: https://curiouslearning.atlassian.net/browse/FM-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Updated handling on scene-handler for gameplay and retry scene handling (FM-532)

---

src/feedTheMonster.ts

- Fix the prod env dev button appearing
- Open the start screen of FTM live or prod
- Make sure the button is not visible in prod
Ref: [FM-531](https://curiouslearning.atlassian.net/browse/FM-531)
[FM-531]: https://curiouslearning.atlassian.net/browse/FM-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: the dev button in prod env (FM-531)

---

src/common/index.ts
src/common/utils.ts
src/components/riveMonster/rive-monster-component.spec.ts
src/components/riveMonster/rive-monster-component.ts
src/gameStateService/gameStateService.ts
src/scenes/gameplay-scene/gameplay-scene.spec.ts
src/tutorials/MatchLetterPuzzleTutorial/MatchLetterPuzzleTutorial.ts
src/tutorials/base-tutorial/base-tutorial-component.ts
src/tutorials/index.ts
src/tutorials/tutorial-handler.spec.ts

- Added clear tutorial logic using gameStateService and GameScore getAllGameLevelInfo.
- Added a level-end subscription for Tutorial Handler to flag the tutorial as cleared.
- Updated the logic on how the tutorial drag computes for the drop location.
- Start FTM app.
- Play on level 1, segment 1 of the puzzle.
- Tutorial should show up.
- The drag tutorial should drag where the hitbox is and it is close to the Rive monster.
- After clearing the level 1 game, when we repeat the level. The tutorial should not show up.
Ref: [FM-542](https://curiouslearning.atlassian.net/browse/FM-542)
Ref: [FM-510](https://curiouslearning.atlassian.net/browse/FM-510)
[FM-542]: https://curiouslearning.atlassian.net/browse/FM-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

Feat: Updated Tutorial Drag Drop Point and Added Clear Tutorial Feature (FM-510 & FM-542).

---

src/common/stone-config/stone-config.spec.ts
src/common/stone-config/stone-config.ts
src/components/stone-handler/stone-handler.spec.ts
src/components/stone-handler/stone-handler.ts
src/gameStateService/gameStateService.ts
src/scenes/gameplay-scene/gameplay-scene.spec.ts
src/scenes/gameplay-scene/gameplay-scene.ts

- Removed Timer from Stone-handler.
- Moved Timer draw to gameplay-scene.
- Added a proper flag to properly load Timer in sync with Stone-handler after loading the stones.
- Updated gameStateService to provide the proper tutorial details flag for future tutorial features relating to timer.
- Created a method handleTimerUpdate in gameplay-scene, to handle the logic of the Timer drawing.
- Code clean ups via adding comments and updating test specs on the relating files.
- Run FTM app.
- Play the level one, tutorial should show up as is.
- Stone letters should work as is.
- No issues in terms of loading the stones or gameplay.
Ref: [FM-557](https://curiouslearning.atlassian.net/browse/FM-557)
[FM-557]: https://curiouslearning.atlassian.net/browse/FM-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …

optimized: Removed Timer from Stone-handler (FM-557).

---

src/components/stone-handler/stone-handler.ts

- Update logic on draw word stones in stone-handler.
- Run FTM app.
- Play the level one, tutorial should show up as is.
- Stone letters should work as is.
- No issues in terms of loading the stones or gameplay.
Ref: [FM-557](https://curiouslearning.atlassian.net/browse/FM-557)
[FM-557]: https://curiouslearning.atlassian.net/browse/FM-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Updated logic to stone draws on word puzzles (FM-557).

---

src/scenes/gameplay-scene/gameplay-scene.spec.ts
src/scenes/gameplay-scene/gameplay-scene.ts
src/tutorials/MatchLetterPuzzleTutorial/MatchLetterPuzzleTutorial.ts

- Added delta time to ensure that the SFX plays only at the start of the timer.
- Select any level to play
- In gameplay scene make sure the start sfx will play when the timer starts
- Make sure the sfx timer starts dont play when tapping the monster
Ref: [FM-650](https://curiouslearning.atlassian.net/browse/FM-650)

fix: the issue on sfx playing when tapping the monster and the delay start of the start timer sfx in low end devices (FM-650)

---

src/components/prompt-text/prompt-text.ts

- src/components/prompt-text/prompt-text.ts
- Check the matchfirst levels for RTL languages (eg. - Farsi level 36)
Ref: [CR-391](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-391)
[CR-391]: https://curiouslearning.atlassian.net/browse/CR-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: CR-391 Letter Highlighting issue fixed for  Matchfirst level in RTL languages 

---

src/scenes/gameplay-scene/gameplay-scene.ts

- move the timerStartSFXPlayed flag from loadpuzzle to initnewpuzzle to make sure when initializing new puzzle, timer start sfx will set to false. because putting in loadpuzzle causes the sfx start to play twice after feeding when user is not interacting.
- tap on level 4 or any level that has tutorial
- don't interact or or tap the monster to avoid quick start. wait the stone to drop
- feed the correct stone to the monster 
- carefully listen at the end or feedback make sure the sfx don't play twice.
Ref: [FM-560](https://curiouslearning.atlassian.net/browse/FM-560)
[FM-560]: https://curiouslearning.atlassian.net/browse/FM-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

fix: move the timerStartSFXPlayed flag from loadpuzzle to initnewpuzzle (FM-560)

---

src/gamepuzzles/letterPuzzleLogic/letterPuzzleLogic.spec.ts
src/gamepuzzles/letterPuzzleLogic/letterPuzzleLogic.ts
src/gamepuzzles/puzzleHandler/puzzleHandler.spec.ts
src/gamepuzzles/puzzleHandler/puzzleHandler.ts
src/scenes/gameplay-scene/gameplay-scene.ts

- Removed nested callbacks methods in puzzleHandler.ts and LetterPuzzleLogic.ts
- Cleaned up the ctx method with multiple callbacks by optimizing the code flow and making sure the necessary methods and callbacks that actually needed in puzzleHandler.ts is what is being passed and removed the unnecessary ones.
- Deleted LetterPuzzleLogic.ts handleLetterDrop method as it adds no value and only extending the callbacks.
- Updated the flow in loadPuzzle of gameplay-scene.ts removing the automatic fire of handleLevelend. 
- Start the FTM app.
- Play any game level.
- After solving the last game segment of that puzzle, the expectation is the levelend scene will display after the gameplay-scene has finished playing the audios.
-
Ref: [FM-581](https://curiouslearning.atlassian.net/browse/FM-581) …

fixed: Feedback audio overlaps that plays in the level-end screen when we complete the level real quick (FM-581).

---

src/data/game-score.ts
src/gameStateService/gameStateService.ts

- fix: Prevent 0-1 Star Levels from Contributing to Evolution Progress
- Modified the star count calculation logic to only include levels with 2 or more stars in the total star count used for evolution mechanics, while still displaying the correct visual representation of stars (0-3) in the UI.
- Tap or click any part of the start screen to proceed to the next screen 
- Play level 1: Earn 2 stars
- Play level 2: Earn 2 stars
- Play level 3: Earn 3 stars
- Total accumulated: 7 stars (all counting toward evolution)
- Play level 4: Deliberately earn only 0 or 1 star
- Verify the star is displayed visually in the UI
- Verify the evolution animation does NOT trigger
Ref: [FM-580](https://curiouslearning.atlassian.net/browse/FM-580)
[FM-580]: …

fix: Star Count Increases on Level Failures, skipping Monster Evolution Animation (FM-580)

---

src/components/stone-handler/stone-handler.ts
src/gameStateService/gameStateService.ts
src/gamepuzzles/puzzleHandler/puzzleHandler.ts
src/gamepuzzles/wordPuzzleLogic/wordPuzzleLogic.ts
src/scenes/gameplay-scene/gameplay-scene.ts
src/tutorials/WordPuzzleTutorial/WordPuzzleTutorial.spec.ts
src/tutorials/WordPuzzleTutorial/WordPuzzleTutorial.ts
src/tutorials/base-tutorial/base-tutorial-component.ts
src/tutorials/index.ts
src/tutorials/tutorial-handler.spec.ts

- Optimized stone-handler create stone methods and added comments for better clarity on the logic.
- Added new game state event called WORD_PUZZLE_SUBMITTED_LETTERS_COUNT to allow communication between the puzzle-handler and word puzzle tutorial.
- Added the publish event of WORD_PUZZLE_SUBMITTED_LETTERS_COUNT in puzzle-handler.ts
- Optimized word puzzle tutorial; Removed unnecessary logics like flags and set time out trigger, and duplicate delays. Code clean up and implemented the switching of tutorial dragged based on the stones submitted received from the WORD_PUZZLE_SUBMITTED_LETTERS_COUNT  event.
- Updated the logic in tutorial-handler/index.ts regarding the hide tutorial (it won't hide the tutorial entirely if it is word puzzle tutorial).
- Start FTM app.
- Select any game with …

feat: Updated Tutorial gameplay for Spell (FM-511).

---

src/components/prompt-text/prompt-text.ts

- Implement Letter pulsation in word in Spell
- In the level select screen, select word puzzle level
- First letter in the word bubble pulsates
- After feeding the first letter, Pulsating stops on current letter and starts on the next letter
- Only one letter pulsates at a time
- Pulsation of the letter should be available in all spell puzzles
Ref: [FM-513](https://curiouslearning.atlassian.net/browse/FM-513)
[FM-513]: https://curiouslearning.atlassian.net/browse/FM-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat: Letter pulsation in word in Spell (FM-513)

---

.circleci/config.yml

- Added `invalidate-cloudfront-cache-prod` job in circle ci config.yml
- DEV only, we will need to update the config to trigger in `dev` merge and PR'd there. 
- preliminary [test](https://app.circleci.com/pipelines/github/curiouslearning/FeedTheMonsterJS/4235/workflows/60362b69-e5c0-4770-931f-1f5fdf8c59bd)
Ref: [EN-64](https://curiouslearning.atlassian.net/browse/EN-64)
[EN-64]: https://curiouslearning.atlassian.net/browse/EN-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added cache invalidation job in s3-delpoy-workflow (EN-64)

---

public/index.css

- update z index of the feedback text
- Select any level and play the game
- Feed correct stone
- Feedback title appear and then quickly return to level select screen
- Makesure the feedback title dont show or overlap to the level select screen
Ref: [FM-587](https://curiouslearning.atlassian.net/browse/FM-587)
[FM-587]: https://curiouslearning.atlassian.net/browse/FM-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Feedback text displays in the level-selection screen when we quickly change the screen. (FM-587)

---

src/components/prompt-text/prompt-text.scss
src/components/prompt-text/prompt-text.spec.ts
src/components/prompt-text/prompt-text.ts
src/tutorials/index.ts

- Updated Prompt-Text base HTML, adding a wrapper to handle audio button and slot for text.
- Updated tutorial handler if condition for word puzzle, adding SoundWord in the if flag for spelling puzzles.
- Updated Prompt-Text spec file.
- Run FTM app with `?cr_lang=` set to either Yoruba, Bangla, Hausa, or Sesotho.
- For Yoruba Language, on level 12.
- Play the game and the segment 1 should 
Ref: [FM-516](https://curiouslearning.atlassian.net/browse/FM-516)
[FM-516]: https://curiouslearning.atlassian.net/browse/FM-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added slots and text reveal for audio spelling game (FM-516)

---

src/components/prompt-text/prompt-text.ts

- Removed `this.isLevelHaveTutorial` flag in `isSpellSoundMatchTutorial` method checker to allow slot feature in all Spell Sound Level not just in tutorial.
- Run app in Yoruba language
- Play levels 12 and 25
- There should always be slots rendered in all spell sound level.
Ref: [FM-516](https://curiouslearning.atlassian.net/browse/FM-516)
[FM-516]: https://curiouslearning.atlassian.net/browse/FM-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Changed the logic of slots to show in all spell sound puzzle not just in tutorial (FM-516)

---

src/components/prompt-text/prompt-text.ts

- Remove `this.isSpellSoundMatch() && this.generatePromptSlots();` that was re-added on test branch merging.
- Run FTM app with /?cr_lang=yoruba
- On levels 12 and 12, the text slot should be hidden at first.
Ref: [FM-516](https://curiouslearning.atlassian.net/browse/FM-516)
[FM-516]: https://curiouslearning.atlassian.net/browse/FM-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Re-apply line of code of FM-516 recent changes.

---

src/components/prompt-text/prompt-text.scss
src/components/prompt-text/prompt-text.spec.ts
src/components/prompt-text/prompt-text.ts

- Updated Prompt Bubble rendering by moving it from background-image style of a dive into img html tag.
- Updated the CSS styling to accommodate the new img tag for prompt bubble.
- Run FTM app.
- Play any game level and expect prompt bubble should be properly aligned with the audio button or text prompt.
Ref: [FM-597](https://curiouslearning.atlassian.net/browse/FM-597)
[FM-597]: https://curiouslearning.atlassian.net/browse/FM-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enhancement: Updated prompt bubble rendering and its CSS styling (FM-597)

---

src/components/prompt-text/prompt-text.scss
src/components/prompt-text/prompt-text.ts

- CSS top styling for prompt-bubble-spell-audio has been removed. prompt-center-responsive top styling has been adjusted.
- Added adding margin logic to prompt-content for spell word puzzle to fix the alignment.
- Added logic for checking the text word to determine the appropriate font size and avoid overlapping from the prompt bubble.
- Run FTPM App
- play any game level
- prompt position should be properly aligned and position,
Ref: [FM-597](https://curiouslearning.atlassian.net/browse/FM-597)
[FM-597]: https://curiouslearning.atlassian.net/browse/FM-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enhance: Updated css styling and adjusted how spell word audio puzzle is being handled with styling (FM-597)

---

src/components/prompt-text/prompt-text.scss
src/components/prompt-text/prompt-text.ts

- Update spell sound audio styling.
- Run FTM app
- Play any game level.
- Prompt bubble should always be properly positioned along with its audio button and text content.
Ref: [FM-597](https://curiouslearning.atlassian.net/browse/FM-597)
[FM-597]: https://curiouslearning.atlassian.net/browse/FM-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

enhance: Update css styling for prompt rending (FM-597)
