curiouslearning/FeedTheMonsterJS

- src/scenes/level-selection-scene.js
Added the changes for touch events.
> TouchEventsFixes

- index.css
- index.html
- src/components/prompt-text.js
- src/scenes/level-start-scene.js
- sw.js
Fixed : 
#112,
#113,
#114,
#115,
> Fixed Minor issues

- src/components/stones-layer.js
- src/scenes/level-start-scene.js
> Fixed #119

- build/lang/igbo/ftm_igbo.json
- build/lang/indianenglish/ftm_indianenglish.json
- build/lang/javanese/ftm_javanese.json
- build/lang/kurdish/ftm_kurdish.json
- build/lang/lugandan/ftm_lugandan.json
- build/lang/pashto/ftm_pashto.json
- build/lang/spanish/ftm_spanish.json
- build/lang/thai/ftm_thai.json
- build/lang/tsonga/ftm_tsonga.json
- build/lang/vietnamese/ftm_vietnamese.json
- build/sw.js
- lang/igbo/ftm_igbo.json
- lang/indianenglish/ftm_indianenglish.json
- lang/javanese/ftm_javanese.json
- lang/kurdish/ftm_kurdish.json
- lang/lugandan/ftm_lugandan.json
- lang/pashto/ftm_pashto.json
- lang/spanish/ftm_spanish.json
- lang/thai/ftm_thai.json
- lang/tsonga/ftm_tsonga.json
- lang/vietnamese/ftm_vietnamese.json
- sw-src.js
I have updated the feedback audio's url's!
> #1132 (Updated Feedback audios url's)!

- build/container_app_manifest/dev/web_app_manifest.json
I am adding development manifest from wordpress to s3 bucket!
> Cr-1(Adding  Development json from wordpress to s3 bucket!)

- build/container_app_manifest/dev/web_app_manifest.json
I have added new interactive book to test cr-1 task!
> Cr-1(Added additional interactive book!)

- .github/workflows/release.yml
- package-lock.json
- package.json
We are implementing github release notes process on this repo for automated release notes updates on our slack Channel!
> Implementing GitHub Release notes for release notes!

- build/index.html
- index.html
bumping version in ftm to v1.0.33
> refactor: bumping version in ftm to v1.0.33

- src/scenes/gameplay-scene.ts
Added clearTimeout handling setTimeout reset animation to idle for wordPuzzle game.
Modified File(s)
gameplay-scene.ts
> Fixed [FM-7]: Fixed issue where spit animation not properly playing on word puzzle if you play the game very quick.

- feedTheMonster.ts
- index.html
- src/sceneHandler/scene-handler.ts
"Dev" mode button not clickable in offline mode.
> Fixed [FM-233]: Fixed the Dev button doesn't work on offline mode

- index.html
- src/sceneHandler/scene-handler.ts
Id of toggle button handled properly
> Id of toggle button handled properly

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- created a PR to test CR- 99. it will be reverted after testing.
> testing commit regarding CR 99

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1219
> Revert "testing commit regarding CR 99"

- src/components/index.ts
- src/components/trail-particles.ts
- src/scenes/gameplay-scene.ts
Implemented a sparkle effect when on-click hovering or dragging stone letters.
New file:
1. component/trail-particles.ts
Updated file(s)
1. component/index.ts
2. scenes/gameplay-scenes.ts
> feature [FM-51]: Sparkle on-touch and on-drag effect

- package-lock.json
- package.json
Updated version number in package.json ("version": "1.0.33")
> updated version number in package.json

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1238
> Revert "testing commit"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Its just for testing the version update.
> testing commit

- build/sw.js
- feedTheMonster.ts
- sw-src.js
- Change 1
- it will be reverted after completing the testing.
> testing pr ( just for triggering assests folder in s3 bucket)

- src/components/buttons/pause-button.ts
Feat: Visual Effects for Pressing Buttons
- Updated the visual effect values on pause-button.ts when pressed down.
- Run FTM
- Click Play on start scene.
- Select any game level and pressed pause button on upper right.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-198)
> feat<FM-198>: Visual Effects for Pressing Buttons -> Updated visual effect on Pause button

- build/sw.js
- feedTheMonster.ts
- sw-src.js
Reverts curiouslearning/FeedTheMonsterJS#1258
> Revert "testing pr ( just for triggering assests folder in s3 bucket)"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- it will be reverted after completing the testing.
> testing pr

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
-it will be reverted after completing the testing.
> testing  PR 4

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- it will be reverted after completing the testing.
> testing PR 6

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
-Changes
Change 1
How to test
it will be reverted after completing the testing.
> testing PR 8

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1274
> Revert "testing PR 8"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1270
> Revert "testing  PR 4"

- build/sw.js
- sw-src.js
- Change 1
- Reverting "[testing PR-3](https://github.com/curiouslearning/FeedTheMonsterJS/pull/1269)"
> reverting "testing PR 3"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1268
> Revert "testing pr2"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- It will be reverted after completing the testing.
> Testing PR 3

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1293
> Revert "Testing PR 3"

- .circleci/config.yml
- Circle CI changes
- Tit will be reverted after completing the testing.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/JIRA-CODE)
> Testing PR 7

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- It will be reverted after completing the testing.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/JIRA-CODE)
> Testing PR 11

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- TIt will be reverted after completing the testing.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/JIRA-CODE)
> Testing PR 13

- sw-src.js
- Change 1
- It will be reverted after completing the testing
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/JIRA-CODE)
> Testing PR 14

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1308
> Revert "Testing PR 15"

- sw-src.js
Reverts curiouslearning/FeedTheMonsterJS#1307
> Revert "Testing PR 14"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1306
> Revert "Testing PR 13"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1304
> Revert "Testing PR 11"

- .circleci/config.yml
Reverts curiouslearning/FeedTheMonsterJS#1302
> Revert "Testing PR 9"

- .circleci/config.yml
Reverts curiouslearning/FeedTheMonsterJS#1300
> Revert "Testing PR 7"

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
Reverts curiouslearning/FeedTheMonsterJS#1299
> Revert "Testing PR 6"

- src/components/trail-particles.ts
- Updated the size for multiple screen sizes.
- Updated the color of trail effect.
- Added logic to mix the shape of trail effects with circle and diamond.
- Start FTM app
- Select any level in level selection.
- In the game just press and hover or drag letters, trail effect should be visible.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-51)
> feat<fm-51>: Hover trail effect -> Updated the trail effect 

- src/components/buttons/level-button.ts
- Adjusted the visual effect of level-balloon buttons.
- Start FTM game
- In the level selection when pressing the level button there should be a visual effect when it is clicked.
Ref: [JIRA-CODE](https://curiouslearning.atlassian.net/browse/FM-256)
> feat<FM-256>: Create Reusable Button for Level Balloons: Udjusted button press visual effect.

- new_ftm_language_creation/audio_convertor.py
- new_ftm_language_creation/check_unused_audios_for_lang.py
- audio_convertor.py
- check_unused_audios_for_lang.py
- It's is testing python script for language builds.
> Python script for language builds

- build/lang/hindi/ftm_hindi.json
- lang/hindi/ftm_hindi.json
- Change 1
- Its just for testing and we are reverting it.
> Fix : Hindi Json revert

- build/container_app_manifest/dev/web_app_manifest.json
- Update the Dev Manifest with the latest Colours Interactive Book!
- We can test the new Colours Us English Interactive book by downloading and installing the apk from this [link](https://feedthemonsterdev.curiouscontent.org/APK/development-curious-reader-QA.apk)!
Ref: [AJ-125](https://curiouslearning.atlassian.net/browse/AJ-125)
[AJ-125]: https://curiouslearning.atlassian.net/browse/AJ-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AJ-125 Update the Dev Manifest with the latest Colours Interactive Book!

- build/lang/somali/ftm_somali.json
- lang/somali/ftm_somali.json
- Somali.json
- Check somali feedback text
Ref: No task card.
> Fix : Somali feedback text

- build/lang/oromo/ftm_oromo.json
- lang/oromo/ftm_oromo.json
- ftm_oromo.json
- Check past level 10 of the Oromo dev version.
Ref: No Task
Note : These are the changes requested by iCog group.
> Fix: oromo language build

- .gitignore
- jest.config.js
- package-lock.json
- package.json
- src/components/popups/base-popup/base-popup-component.spec.ts
- feat: installed jest and necessary dependencies
- feat: added new scripts `test` and `test:local`.
- chore: added initial test suite
- `npm i`
- `npm run test` should generate coverage (added to git ignore)
- `npm run test:local` should run tests without coverage (faster, for local development/testing)
Ref: [FM-307](https://curiouslearning.atlassian.net/browse/FM-307)
[FM-307]: https://curiouslearning.atlassian.net/browse/FM-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: unit test integration with config and initial spec file (FM-307)

- build/lang/oromo/ftm_oromo.json
- lang/oromo/ftm_oromo.json
- lang/oromo/ftm_oromo.json
- When I play the development APK and open Oromo,
Then I should see the title as “Hiriyyaa kee soori”.
Ref: [CR-174](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-174)
[CR-174]: https://curiouslearning.atlassian.net/browse/CR-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-174 content changes for Oromo

- build/lang/somali/ftm_somali.json
- lang/somali/ftm_somali.json
- lang/somali/ftm_somali.json
- When I play the development APK and open somali,
Then I should see the title as “Saaxiibkaa Quudii”.
Ref: [CR-175](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-175)
[CR-175]: https://curiouslearning.atlassian.net/browse/CR-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix Cr 175 - content changes for Somali

- build/lang/tigragna/ftm_tigragna.json
- lang/tigragna/ftm_tigragna.json
- lang/tigragna/ftm_tigragna.json
- When I play the development APK and open Tigragna,
Then I should see the title as “ዓርክኻ መግቦ”.
Ref: [CR-176](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-176)
[CR-176]: https://curiouslearning.atlassian.net/browse/CR-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Cr 176 content changes for Tigragna

- build/lang/oromo/ftm_oromo.json
- build/lang/somali/ftm_somali.json
- build/lang/tigragna/ftm_tigragna.json
- lang/oromo/ftm_oromo.json
- lang/somali/ftm_somali.json
- lang/tigragna/ftm_tigragna.json
- lang/oromo/ftm_oromo.json
- lang/oromo/ftm_somali.json
- lang/oromo/ftm_tigirigna.json
- Check all the three languages app title.
> fix: CR-174, CR-175 & CR-176

- .gitignore
- build/.well-known/assetlinks.json
- build/.well-known/assetlinks.json
- .gitignore
- Check for assetlinks.json file is removed from github or not.
> fix: assetlinks.json removed

- .gitignore
- build/.well-known/assetlinks.json
- build/.well-known/assetlinks.json
- .gitignore
- Check for assetlinks.json file is removed from github or not.
> fix: Assetslink changes devbackup

- build/lang/bangla/ftm_bangla.json
- lang/bangla/ftm_bangla.json
- lang/bangla/ftm_bangla.json
-  play Feed The Monster in Bangla in the development Curious Reader
Ref: [CR-182](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-182)
[CR-182]: https://curiouslearning.atlassian.net/browse/CR-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-182 bangla json

- workbox-config.js
- putting back the old code in workbox-config
- In loading screen while wifi is on
- After that, start screen will appear then turn off the wifi
- Go back to FTM App
- Click play button
- make sure everything works normally
Ref: [FM-330](https://curiouslearning.atlassian.net/browse/FM-330)
[FM-330]: https://curiouslearning.atlassian.net/browse/FM-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: assets issue on offline mode (FM-330)

- src/gameStateService/game-state-service.ts
- Added To Do markers on game state service.
- No testing needed
> chore: Added to do markers on what to remove from game state service.

- src/components/popups/base-popup/base-popup-component.ts
- src/components/popups/pause-popup/pause-popup-component.ts
- Fix stuck when repeatedly click on the buittons in pause popup
- Play any level
- Pause the game
- While popup showing repeatedly click on the retry and map buttons
- Make sure it wont freeze
> fix: stuck when repeatedly click on the buttons in pause popup (FM-342)

- build/index.html
- index.html
- package-lock.json
- package.json
- changed the version from 1.0.36 to 1.0.37
> main branch version changes

- CHANGELOG.md
- build/index.html
- package-lock.json
- package.json
- public/index.html
- CHANGELOG.md
- package.json
- package-lock.json
- index.html
- Check the version number.
> fix:  develop branch version update

- src/components/background/base-background/base-background-component.spec.ts
- src/components/buttons/base-button-component/base-button-component.spec.ts
- src/components/buttons/base-button-component/base-button-component.ts
- src/components/buttons/index.ts
- src/components/buttons/play-button.ts
- src/components/buttons/play-button/play-button.scss
- src/components/buttons/play-button/play-button.ts
- src/components/timerHtml/timerHtml.ts
- src/scenes/index.ts
- src/scenes/start-scene.ts
- src/scenes/start-scene/start-scene.spec.ts
- src/scenes/start-scene/start-scene.ts
- Replaced the start scene background from Canvas to HTML implementation.
- Updated Timer component creation, originally using a background class, now points to the ID background. So it won't bug out due to the implementation of Start Scene HTML background.
- Updated base button component by adding a _destroy method.
- Added test cases for background component and updated test case of base button by adding the destroy test scenario.
- Run FTM app on browser.
- In start scene, press F12 to check if the rendered Play Button and Background are HTML implementation by viewing them on the DOM tree.
- Press Play and select any game level.
- In the game level, there should be a timer rendered.
Ref: [FM-288](https://curiouslearning.atlassian.net/browse/FM-288)
[FM-288]: …
> feat: Updated Start Scene from canvas implementation to HTML.

- src/components/buttons/base-button-component/base-button-component.ts
- src/components/popups/confirm-popup/confirm-popup-component.spec.ts
- src/components/popups/confirm-popup/confirm-popup-component.ts
- src/components/popups/pause-popup/pause-popup-component.spec.ts
- src/components/popups/pause-popup/pause-popup-component.ts
- Fix buttons in the popup that causing audio stack and game stuck
- Play any level
- In Gameplay screen
- Click pause button
- Repeatedly click buttons in the popup
- Make sure it will not break the game
- Make sure no audio stacking
Ref: [FM-342](https://curiouslearning.atlassian.net/browse/FM-342)
[FM-342]: https://curiouslearning.atlassian.net/browse/FM-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: popup button issues (FM-342)

- src/components/level-field/level-field-component.spec.ts
- src/components/level-indicator/level-indicator.spec.ts
- Updated spec file for level-field-component.spec.ts
- Create spec file for level-indicator.
- Run npm run test level-indicator.spec.ts
- npm run test level-field-component.spec.ts
> test: Updated test suites for level field component and added new test suite for level indicator.

- src/components/prompt-text.ts
-Check for the match first levels in Bangla and some other lanuages.
Ref: [CR-227](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-227)
[CR-227]: https://curiouslearning.atlassian.net/browse/CR-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-227 changes for matchfirst level ([]) brackets develop branch

- src/components/buttons/level-button.ts
- src/scenes/level-selection-scene.ts
- Fix the issue when the pulse is animating even there's no balloon or level
- Check and make sure pulse is animating in the last level if the last level is unlocked.
- Check this fix in other language that has a few levels like georgian
Ref: [FM-353](https://curiouslearning.atlassian.net/browse/FM-353)
[FM-353]: https://curiouslearning.atlassian.net/browse/FM-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-353 fix pulse issue in level select scene (FM-353)

- .circleci/config.yml
- package-lock.json
- package.json
> feat: build and deploy

- .circleci/config.yml
- .gitignore
- circle ci config, to require build to finish before deploying to s3
- added coverage to git ignore
- observed in circle ci dashboard, build should be finished first before deploying.
> fix: build race condition

- sw-src.js
- sw-src.js
- It will be reverted after completing the testing
Ref: [test](https://curiouslearning.atlassian.net/browse/<JIRA-CODE>)
> test: test env cache testing

- sw-src.js
- sw-src.js
- Cache some languages in online mode and than test all of those languages in offline mode.
Ref: [CR-268](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-268)
[CR-268]: https://curiouslearning.atlassian.net/browse/CR-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-268 test env caching

- lang/gujarati/ftm_gujarati.json
- lang/gujarati/ftm_gujarati.json
- Check Gujrati language in test build
Ref: [CR-262](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-262)
[CR-262]: https://curiouslearning.atlassian.net/browse/CR-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Cr 262 Test build and verify "Gujarati" FTM

- lang/farsitest/ftm_farsitest.json
- lang/farsitest/ftm_farsitest.json
- Check the farsi level 2 stone text
Ref: [CR-267](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-267)
[CR-267]: https://curiouslearning.atlassian.net/browse/CR-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-267 farsi json rebuild

- src/components/prompt-text.ts
- Test for levels in LTR languages for letterInWord prompt text 
Ref: [CR-258](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-258)
[CR-258]: https://curiouslearning.atlassian.net/browse/CR-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR 258 Alignment  & overlapping fixed for LTR languages in LetterInWord

- src/components/prompt-text.ts
- Check for word levels prompt text in LTR languages
Ref: [CR-258](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-258)
[CR-258]: https://curiouslearning.atlassian.net/browse/CR-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR 258 LTR word level UI prompt text fix

- src/components/prompt-text.ts
- Check for RTL letterinword levels for overlap issues
Ref: [CR-286](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-286)
[CR-286]: https://curiouslearning.atlassian.net/browse/CR-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR 286 RTL letterinword

- src/components/prompt-text.ts
- Check for RTL letterInword levels for alignment issue
Ref: [CR-286](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-286)
[CR-286]: https://curiouslearning.atlassian.net/browse/CR-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Cr 286 RTL alignment issue 

- lang/telugu/ftm_telugu.json
- lang/telugu/ftm_telugu.json
- Telugu Level 11 and Level 14 changes are present as [noted in the QA](https://docs.google.com/document/d/1arf6MFZwiprHWvGGa9Wcmu1WuYRCaP03k1r0V_4yZ3k/edit?usp=sharing).
Ref: [CR-275](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-275)
[CR-275]: https://curiouslearning.atlassian.net/browse/CR-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-275 updated ftm_telugu.json

- lang/telugu/ftm_telugu.json
- lang/telugu/ftm_telugu.json
- Check for Level 11 and Level 14 changes should be present as [noted in the QA DOC
](https://docs.google.com/document/d/1arf6MFZwiprHWvGGa9Wcmu1WuYRCaP03k1r0V_4yZ3k/edit?usp=sharing).
Ref: [CR-275](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-275)
[CR-275]: https://curiouslearning.atlassian.net/browse/CR-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-275 updated telugu json

- src/data/game-score.ts
- Stars update if more than the previous star count, instead of adding/appending towards the existing star count
- Download the latest dev build of FTM and download the game.
- Play 2 levels and score 5 stars in total.
- Then Replay the level which you scored 2 stars and get 3 stars.
- Once we complete the replay of the level we can observe the evolution animation playing in the level end screen. 
Ref: [FM-409](https://curiouslearning.atlassian.net/browse/FM-409)
[FM-409]: https://curiouslearning.atlassian.net/browse/FM-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-409 Level replay adds up to the total accumulated stars

- build/lang/punjabi/ftm_punjabi.json
- lang/punjabi/ftm_punjabi.json
- build/lang/punjabi/ftm_punjabi.json
- lang/punjabi/ftm_punjabi.json
- Check for Punjabi build
Ref: [CR-294](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-294)
[CR-294]: https://curiouslearning.atlassian.net/browse/CR-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR 294 Test and verify Punjabi (updated Content)

- src/Firebase/base-firebase-integration.ts
- src/components/buttons/play-button.ts
- src/scenes/start-scene.ts
> Resolving Conflicts!

- package.json
- src/constants/index.ts
- FM-490 changed the url to point current directory
- Download and install test env curious reader app and select a language.
- Download a FTM app in any of the language and start playing the game.
- Collect 8 stars to trigger the evolution and observe the issue.
Ref: [FM-490](https://curiouslearning.atlassian.net/browse/Fm-490)
[FM-490]: https://curiouslearning.atlassian.net/browse/FM-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-490 changed the url to point current directory

- src/components/cursor/cursor-component.ts
- src/components/index.ts
- src/components/trail-effects/index.spec.ts
- src/components/trail-effects/index.ts
- src/components/trail-effects/trail-particles.ts
- src/gameSettingsService/gameSettingsService.ts
- src/scenes/gameplay-scene/gameplay-scene.spec.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- Cleaned up Trail EFFECT TOGGLE event from GameSettingService, Gameplay-Scene and TrailParticles.
- Created a Cursor Component with ease of adding and removing event methods.
- Created a TrailEffectHandler that will be using the Cursor Component and will be handling trail effects.
- Start the FTM app
- Select any game level
- You should be able to see the same trail effect when pressing down.
Ref: [FM-470](https://curiouslearning.atlassian.net/browse/FM-470)
[FM-470]: https://curiouslearning.atlassian.net/browse/FM-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Added Cursor Component and TrailEffectHandler (FM-470).

- public/index.css
- Added display none on CSS.
- There should be no DEV button in start scene page.
Ref: [FM-527](https://curiouslearning.atlassian.net/browse/FM-527)
[FM-527]: https://curiouslearning.atlassian.net/browse/FM-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Hide dev button (FM-527).

- src/components/trail-effects/index.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- src/tutorials/LetterPuzzleTutorial/LetterPuzzleTutorial.ts
- src/tutorials/base-tutorial/base-tutorial-component.ts
- Updated condition on how the tutorial is being rendered.
- Updated trail effects conditions on being rendered.
- Code clean up on gameplay-scene.
- Tutorial should appear a quick start before the game starts.
- Tutorial should show letter being drag during gameplay as a guide.
- Tutorial guide should stop the moment the letter has been dropped to the hitbox.
- Trail effect should only show and create trails during gameplay.
Ref: [FM-482](https://curiouslearning.atlassian.net/browse/FM-482)
Ref: [FM-470](https://curiouslearning.atlassian.net/browse/FM-470)
[FM-482]: https://curiouslearning.atlassian.net/browse/FM-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FM-470]: https://curiouslearning.atlassian.net/browse/FM-470?atlOrigin=eyJpIjoiN …
> feat: Code clean up and updated conditions on rendering tutorial and trail effects (FM-482 and FM-470)

- src/feedTheMonster.ts
- src/gameStateService/gameStateService.ts
- src/sceneHandler/scene-handler.ts
- src/scenes/start-scene/start-scene.ts
- Added dispose process before scene-handler gets deleted in FeedTheMonster.ts
- Added condition to make sure no redundant triggering of scene change in scene-handler.
- Open FTM app
- Close it
-Then re-open FTM app
-It should be working normally.
Ref: [FM-532](https://curiouslearning.atlassian.net/browse/FM-532)
[FM-532]: https://curiouslearning.atlassian.net/browse/FM-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: WIP fix for FTM stress reloading (FM-532).

- src/feedTheMonster.ts
- src/gameStateService/gameStateService.ts
- src/sceneHandler/scene-handler.ts
- src/scenes/start-scene/start-scene.ts
-Added dispose process before scene-handler gets deleted in FeedTheMonster.ts
-Added condition to make sure no redundant triggering of scene change in scene-handler.
-Open FTM app
-Close it
-Then re-open FTM app
-It should be working normally.
Ref: [FM-532](https://curiouslearning.atlassian.net/browse/FM-532)
[FM-532]: https://curiouslearning.atlassian.net/browse/FM-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Fix for FTM stress reloading (FM-532)

- lang/bangla/ftm_bangla.json
- lang/bangla/ftm_bangla.json
- Check for feedback [audio](https://feedthemonster.curiouscontent.org/lang/bangla/audios/fantastic.mp3)
Ref: [CR-321](https://curiouslearning.atlassian.net/jira/software/projects/CR/boards/7?selectedIssue=CR-321)
[CR-321]: https://curiouslearning.atlassian.net/browse/CR-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-321 - Bangla json fix!

- src/components/prompt-text/prompt-text.scss
- src/components/prompt-text/prompt-text.spec.ts
- src/components/prompt-text/prompt-text.ts
- Add Pulsating effect of the first letter of the word
- In level select, select any letter in word level (e.g: lvl 5 or 6)
- Make sure the first letter has pulsating effect
Ref: [Fm-509](https://curiouslearning.atlassian.net/browse/Fm-509)
> feat: [Gameplay] Pulsating effect of the first letter of the word (Fm-509)

- src/Firebase/firebase-event-test.test.ts
- src/Firebase/firebase-integration.spec.ts
- Added QA unit test for FTM firebase custom event logging for Event Logs!
- I have test cases for all the firebase events for whom user story have been created!
- In order to test the changes user can open the repo and run "npm run test" command in the terminal for checking the test cases!
Ref: [AJ-345](https://curiouslearning.atlassian.net/browse/AJ-345)
Ref: [AJ-346](https://curiouslearning.atlassian.net/browse/AJ-346)
Ref: [AJ-347](https://curiouslearning.atlassian.net/browse/AJ-347)
Ref: [AJ-348](https://curiouslearning.atlassian.net/browse/AJ-348)
Ref: [AJ-349](https://curiouslearning.atlassian.net/browse/AJ-349)
Ref: [AJ-350](https://curiouslearning.atlassian.net/browse/AJ-350)
Ref: [AJ-351](https://curiouslearning.atlassian.net/browse/AJ-351)
[AJ-345]: …
> chore: QA unit test for FTM firebase custom event logging for Event Logs!

- src/common/index.ts
- src/common/utils.ts
- src/components/prompt-text/prompt-text.scss
- src/components/prompt-text/prompt-text.ts
- src/scenes/gameplay-scene/gameplay-scene.spec.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- src/tutorials/AudioPuzzleTutorial/AudioPuzzleTutorial.spec.ts
- src/tutorials/AudioPuzzleTutorial/AudioPuzzleTutorial.ts
- src/tutorials/base-tutorial/base-tutorial-component.ts
- src/tutorials/base-tutorial/tutorial.scss
- src/tutorials/index.ts
- Implement Audio Puzzle Tutorial Using Reusable Component (FM-484)
- Transition from audio tutorial to Stone dragging tutorial for the MatchSound (FM-549)
- Word is replayed when sound icon is tapped (player initiated) (FM-517)
- Word is replayed when sound icon is tapped (instructive pointer initiated) (FM-518)
- Open the FTM start screen.
- Tap or click anywhere on the start screen to proceed.
- Select the first audio or match sound level from level select screen.
- Ensure that the first audio or match sound level includes a tutorial.
- Verify that the audio plays automatically after 3 seconds when the tutorial is active.
- Clicking the sound button should play the audio again.
- When selecting any match sound level other than the first one, the tutorial should not appear.
Ref: …
> Feat: Match sound tutorial (FM-484, FM-549, FM-417, FM-418)

- src/tutorials/MatchLetterPuzzleTutorial/MatchLetterPuzzleTutorial.ts
- Adding console logs for the MatchLetterPuzzleTutorial for now to better observe and understand what’s really happening during development, since it’s currently difficult for us to see or replicate the issue.
Ref: [FM-568](https://curiouslearning.atlassian.net/browse/FM-568)
[FM-568]: https://curiouslearning.atlassian.net/browse/FM-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> debug: add console to debug the issue (FM-568)

- lang/tamil/ftm_tamil.json
- lang/tamil/ftm_tamil.json
- Check tamil language in test apk. It should only contain two feedback phrases.
Ref: [CR-388](CR-388)
[CR-388]: https://curiouslearning.atlassian.net/browse/CR-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: CR-388 Updated tamil language json 

- src/tutorials/MatchLetterPuzzleTutorial/MatchLetterPuzzleTutorial.ts
Ref: [FM-568](https://curiouslearning.atlassian.net/browse/FM-568)
[FM-568]: https://curiouslearning.atlassian.net/browse/FM-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> revert: console log for debugging purposes (FM-568)

- src/common/stone-config/stone-config.ts
- Fixed the size of the font as the image size
- Play the game level from 61-73 on kannada language
Ref: [FM-589](https://curiouslearning.atlassian.net/browse/FM-589>)
[FM-589]: https://curiouslearning.atlassian.net/browse/FM-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-589 Kannada language: stone to letter fit

- src/components/prompt-text/prompt-text.scss
- src/components/prompt-text/prompt-text.spec.ts
- src/components/prompt-text/prompt-text.ts
- src/gamepuzzles/puzzleHandler/puzzleHandler.spec.ts
- src/gamepuzzles/puzzleHandler/puzzleHandler.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- Updated Prompt-Text.scss
- Updated Prompt-Text spec for testing.
- Refactor Prompt-Text class by optimizing how the prompt renders text and audio button.
- Start FTM app
- Play any game level.
- Prompt Text should display and work as intended.
Ref: [FM-586](https://curiouslearning.atlassian.net/browse/FM-586)
[FM-586]: https://curiouslearning.atlassian.net/browse/FM-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> optimize: Refactor Prompt Text Class (FM-586)

- src/tutorials/AudioPuzzleTutorial/AudioPuzzleTutorial.ts
- src/tutorials/MatchLetterPuzzleTutorial/MatchLetterPuzzleTutorial.ts
- src/tutorials/QuickStartTutorial/QuickStartTutorial.ts
- src/tutorials/WordPuzzleTutorial/WordPuzzleTutorial.ts
- src/tutorials/base-tutorial/base-tutorial-component.ts
- Code enhancement
- The drag tutorial gets interrupted when device screen goes to sleep while the tutorial is playing. 
Ref: [FM-568](https://curiouslearning.atlassian.net/browse/FM-568)
[FM-568]: https://curiouslearning.atlassian.net/browse/FM-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-568 The drag tutorial gets interrupted when device screen goes to sleep while the tutorial is playing. 

- src/components/prompt-text/prompt-text.scss
- src/components/prompt-text/prompt-text.spec.ts
- src/components/prompt-text/prompt-text.ts
- src/gameStateService/gameStateService.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- src/tutorials/WordPuzzleTutorial/WordPuzzleTutorial.ts
- src/tutorials/index.ts
- Modified the rendering of text slots in Prompt Text.
- Added logics on triggering the Text Slots via quick start event, timer and added clean up logic so slots are hidden and displayed each level.
- Added a patch fix for a tutorial undefined error.
- Added comments for code clean up.
- Run FTM app with /?cr_lang=Yoruba
- Play game levels 12 and 25
Ref: [FM-516](https://curiouslearning.atlassian.net/browse/FM-516)
[FM-516]: https://curiouslearning.atlassian.net/browse/FM-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Updated spell word audio logic and added patch fix to tutorial error undefined (FM-516).

- src/components/timer-ticking.ts
- src/scenes/gameplay-scene/gameplay-scene.spec.ts
- src/scenes/gameplay-scene/gameplay-scene.ts
- Implement `determineNextStep` before calling the `loadPuzzle`.
- Run FTM app.
- Play any game level.
- Game level should load each game segments properly.
Ref: [FM-603](https://curiouslearning.atlassian.net/browse/FM-603)
[FM-603]: https://curiouslearning.atlassian.net/browse/FM-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Support treasure chest in between gameplay (FM-603)

- public/index.css
- src/feedTheMonster.ts
- src/miniGame/miniGames/treasureChest/treasureChestAnimation.ts
- src/miniGame/miniGames/treasureChest/treasureStones.ts
- Fixed Tap Interaction Not Registering for Top Stone When Multiple Stones Overlap
- Fixed Position issue on web version
- Play mini level on web and mobile screens
Ref: [FM-692](https://curiouslearning.atlassian.net/browse/FM-692)
[FM-692]: https://curiouslearning.atlassian.net/browse/FM-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: FM-692 Tap Interaction Not Registering for Top Stone When Multiple Stones Overlap & position issue in Web version.

- public/index.css
- src/feedTheMonster.ts
- src/miniGame/miniGames/treasureChest/treasureChestAnimation.ts
- src/miniGame/miniGames/treasureChest/treasureStones.ts
> Develop to test code merge
